### ISSUE TITLE
Impossible to install module due to dependencies

### ISSUE THREAD

**Issue by paugnu** [boolfly/product-label#1]
Hi,

First of all, thanks for this module. However, it is not possible to install it:
* It depends on boolfly/base module, which is not available anywhere
* composer install is not possible either (not released version and dependencies not available)

May I ask if you're planning to fix this?

Thanks!

**Comment by mrkhoa99** [comment]
@catgento let me check again.
@thaopw could you check again?

**Comment by kanzelsberger** [comment]
I have a similar problem, cannot install ... but it is because this module requires php 7.1, while I'm running php 7.2 ... can you update required version of php to include 7.2?

**Comment by mrkhoa99** [comment]
@kanzelsberger my team is checking now. Thanks for reporting.

**Comment by mrkhoa99** [comment]
@paugnu @kanzelsberger updated packagist. It's working

`composer require boolfly/module-product-label`

<img width="345" alt="fish Users mrkhoa www boolfly-composer 2020-04-22 14-18-27" src="https://user-images.githubusercontent.com/6185767/79952682-fc436680-84a4-11ea-8879-81bb7defb9bc.png">
