### ISSUE TITLE
Edit existing rules

### ISSUE THREAD

**Issue by kanzelsberger** [boolfly/product-label#2]
Hi,

we created a new Product Label rule. After that if we want to edit, there's only this text displayed in Rule Manager:

`Not registered handle boolfly_label_rule_listing_data_source`

Under Boolfly icon there's nothing available as well.

**Comment by mrkhoa99** [comment]
@kanzelsberger ok let me check again. Thank you for reporting the issue.

**Comment by mrkhoa99** [comment]
@kanzelsberger what is your PHP version? Can you try with #3 fix?
