### ISSUE TITLE
Using the Identifier entity_id instead of row_id while saving the condition for sku

### ISSUE THREAD

**Issue by girishanand** [boolfly/product-label#6]
Hello @mrkhoa99 ,

Hope you are doing good, We are using the EE 2.4.0 and the issue we are having is when we use the condition for attribute **sku** with any condition the data saving in the boolfly_productlabel_product_index_rule table is using the product row_id and not the entity_id.
Is that possible to fix this issue and use entity_id instead ?

Below is the fix and to be applied on the function used in below files
boolfly/module-product-label/Helper/Rule.php
boolfly/module-product-label/Model/Condition/Sql/Builder.php
boolfly/module-product-label/Model/Indexer/Full.php
boolfly/module-product-label/Model/Indexer/Row.php

```
private function getProductIdentifierField()
    {
        if ($this->productEntityIdentifierField === null) {
            $this->productEntityIdentifierField = $this->getMetadataPool()
                ->getMetadata(ProductInterface::class)
                ->getIdentifierField();
        }
        return $this->productEntityIdentifierField;
    }

```
Kindly let me know in case you want me to create a commit instead if I find something

**Comment by mrkhoa99** [comment]
@girishanand I'm happy to see your commits! Thank you.

**Comment by girishanand** [comment]
Thanks @mrkhoa99 ,

I created the one just now.
https://github.com/boolfly/product-label/pull/7
